### PR TITLE
update packages

### PR DESCRIPTION
**Pull request by hrueger**
Hi @Julusian,
I ran into the problem you described here: https://github.com/prebuild/node-gyp-build/pull/46#issue-1205729151 with exactly this library, though it took me a day to figure out what the problem was ;-)

I believe this PR fixes it. I did update all the other packages, too, and thus I had to regenerate the snapshots (it's just format changes).

Currently waiting for the GitHub Actions build in order to test this.

### CODE REVIEW

**Comment by hrueger** [comment]
Unfortunately, I'm still stuck with the same error:
image

Maybe it is not loading the correct .node file? In `app.asar/node_modules/@julusian/freetype2` there is (correctly) no `build` folder, just the `prebuilds` dir. The files in there are also correct:
image

**Comment by hrueger** [comment]
This does, however, seem to fix the prebuilds detection (?) ?
Yesterday, with same electron-builder build command, I got a `build/Release` folder in the final app.asar with a .node file being arm64:
```
Hanness-MacBook-Pro:node_modules Hannes$ file \@julusian/freetype2/build/Release/freetype2.node 
@julusian/freetype2/build/Release/freetype2.node: Mach-O 64-bit bundle arm64
```
This is strange though, as the GitHub Action runner is a x86_64 based machine...

Maybe electron/universal didn't merge the asar correctly?

**Comment by Julusian** [comment]
Are other libs such as `serialport`, `@julusian/midi` and `@julusian/jpeg-turbo` all loading?
If so, I would be tempted to switch this lib away from `node-gyp-build` and use the same thing I wrote for `@julusian/jpeg-turbo`

There are a few bits in this that I really should have done between forking and publishing..

**Comment by hrueger** [comment]
Yes, it only happens with this library. The others are fine.

**Comment by hrueger** [comment]
I tried to update the build toolchain to the same as https://github.com/Julusian/node-jpeg-turbo, but I don't think I'm familiar with cmake-js to move from `node-gyp` to `cmake-js`...

**Comment by hrueger** [comment]
superseded by #2 :smile:

**Comment by Julusian** [comment]
could you try using a yarn resolution (or equivalent) to pull in @julusian/freetype2 v1.1.0-0
It looks to be working to me, someone else checking it works before publishing as a stable would be good :)

**Comment by hrueger** [comment]
Sure 👍 working on it.

**Comment by hrueger** [comment]
Testbuild is running, takes about 20 Minutes.

**Comment by hrueger** [comment]
Yes, it works now 👍👍 Thanks a lot.

**Comment by Julusian** [comment]
Perfect, I've published it at 1.1.0 now too, so it can be pulled in without needing an override

**Comment by hrueger** [comment]
Sounds great, thanks 👍

**Pull request closed without merging**
